export const Users = [
  {
    id: 1,
    profilePicture: "pictures/photo1.jpg",
    username: "Milan Milanovic",
  },
  {
    id: 2,
    profilePicture: "pictures/photo2.jpg",
    username: "Milos Milosevic",
  },
  {
    id: 3,
    profilePicture: "pictures/photo3.jpg",
    username: "Sanja Vasilic",
  },
  {
    id: 4,
    profilePicture: "pictures/photo4.jpg",
    username: "Vesna Markovic",
  },
  {
    id: 5,
    profilePicture: "pictures/photo5.jpg",
    username: "Nikola Nikolic",
  },
  {
    id: 6,
    profilePicture: "pictures/photo6.jpg",
    username: "Njegos Tomicic",
  },
  {
    id: 7,
    profilePicture: "pictures/photo7.jpg",
    username: "Srdjan Aleksic",
  },
  {
    id: 8,
    profilePicture: "pictures/photo8.jpeg",
    username: "Aleksa Aleksic",
  },
  {
    id: 9,
    profilePicture: "picture/photo9.jpeg",
    username: "Vedran Tomic",
  },
  {
    id: 10,
    profilePicture: "pictures/10.jpg",
    username: "Milovan Milovanovic",
  },
];

export const Posts = [
  {
    id: 1,
    desc: ".",
    photo: "pictures/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "pictures/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Live, love, TRAVEL, laugh.",
    photo: "pictures/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "pictures/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    desc: "Omiljena serija!!",
    photo: "pictures/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "pictures/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Dogg lover.",
    photo: "pictures/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "pictures/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "ICONS!",
    photo: "pictures/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "pictures/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
